python3 test_intralayer.py \
	--architecture simba \
	--app_name vit \
	--alg GA \
	--encode_type num \
	--dataflow ours \
	--chiplet_num_max 36 \
	--chiplet_num_min 1 \
	--chiplet_parallel K_stable \
	--PE_parallel All \
	--save_all_records 0 \
	--layer_fuse_tag 1 \
	--optimization_objective edp